### PR TITLE
OpenCV3 support added

### PR DESCRIPTION
**Pull request by cpaxton**

### CODE REVIEW

**Comment by ahundt** [comment]
Despite the confusion in https://github.com/code-iai/iai_kinect2/issues/200, this pull request should still be correct and both forwards and backwards compatible.

**Comment by wiedemeyer** [comment]
Hi,
I already looked into the OpenCV 3.0 support. I added those changes to the devel branch some time ago. But even if the code might support OpenCV 3.0, it will not work, because cv_bridge is compiled against OpenCV 2.4.x in Indigo and Jade.

**Comment by ahundt** [comment]
@wiedemeyer I don't think your changes will work on all versions of opencv2, particularly the #ifdef parts (see my ifdefs for comparison)

**Comment by wiedemeyer** [comment]
@ahundt I used the example from the OpenCV transition guide, here: http://docs.opencv.org/master/db/dfa/tutorial_transition_guide.html#tutorial_transition_both
It also mentions to not use `CV_VERSION_MAJOR`.

**Comment by ahundt** [comment]
@wiedemeyer good point, missed that. Thanks

**Comment by wiedemeyer** [comment]
I merged the devel branch commits to the master, therefore I will close this PR now.
Thanks for providing a PR.

**Pull request closed without merging**
