### PR TITLE
Fix broken README.md

### PR DESCRIPTION
**Pull request by furushchev**
- fix broken style of markdown
- better code highlighting

### CODE REVIEW

**Comment by eisoku9618** [comment]
``kinect2_calibration/README.md`` is also broken and I fixed it in https://github.com/furushchev/iai_kinect2/pull/1

**Comment by furushchev** [comment]
@eisoku9618 Danke schön!

**Comment by furushchev** [comment]
@eisoku9618 Danke schön!

**Comment by bbferka** [comment]
@furushchev  I  noticed your PR late and merged a fix that was not as complete. would you mind solving the conflicts and reopening the PR.

**Comment by furushchev** [comment]
@bbferka Done!

**Comment by furushchev** [comment]
@bbferka Sorry, I misunderstood. Now I closed this PR.

**Comment by eisoku9618** [comment]
@furushchev https://github.com/code-iai/iai_kinect2/pull/433 is not enough and https://github.com/furushchev/iai_kinect2/pull/1 is necessary, so I think you need to reopen this PR

**Comment by furushchev** [comment]
@eisoku9618 OK, reopened.

**Pull request merged**
