### PR TITLE
CMake build fixes for OS X for CL.hpp based on fixes in libfreenect2

### PR DESCRIPTION
**Pull request by ahundt**

### CODE REVIEW

**Comment by wiedemeyer** [comment]
Thanks for the PR. I just have some questions.
Why does OS X needs that header, what is wrong with the one provided by OS X?
And why did you add `CXX` to the `project(...)`, isn't it enabled by default anyway?

**Comment by ahundt** [comment]
regarding CXX I think it is just recommended by CMake in their docs. I'm also having some issues where the flags set break clang compilation but for now I'm just using a hardcoded -std=c++11 flag. The header simply doesn't seem to be present on OS X, and this is the exact header found in libfreenect2 for the same reason. I guess since this projects uses libfreenect2 it may be possible to find the one they defined. I didn't think of that possibility for some reason when I first made the change, perhaps they should install it so dependents can use it? I just checked and they currently do not.

**Comment by xlz** [comment]
I think OP meant including cl.hpp. libfreenect2 includes one copy of cl.hpp internally. Part of the reason is System integrity protection on Mac OS X which prevent root from doing things https://github.com/OpenKinect/libfreenect2/issues/430

**Comment by ahundt** [comment]
Yeah that's what I meant

**Comment by ahundt** [comment]
Per @xlz in https://github.com/OpenKinect/libfreenect2/issues/595 they will not be installing cl.hpp, so it makes sense to include it here.

**Comment by wiedemeyer** [comment]
merged the PR. Thanks for detailed description of the problem.

**Pull request merged**
