### PR TITLE
recorder for iai_kinect bridge using rosbag

### PR DESCRIPTION
**Pull request by buntyke**
Kinect Studio in windows has the option to record and playback data. For this, I have implemented the kinect2_recorder package that can be used to record rosbag files and playback the data. I think this feature might be useful to many users. Please look into this pull request Thiemo.

I have implemented it similar to the kinect2_viewer that you have written. Let me know if you have any questions. Hope this is helpful :)

Cheers,
Nishanth

### CODE REVIEW

**Comment by buntyke** [comment]
Should I have rather sent the pull request to the devel branch?

**Comment by wiedemeyer** [comment]
Hi Nishanth,
thanks for the pull request. I didn't had much time to look into it yet. But I have some questions regarding the pull request.
What is the use-case? Why not simply using `rosbag record <topics>` and `rosbag play <bagfile>`? For what is a dedicated recorder needed, what are the advantages?

**Comment by buntyke** [comment]
Hi Thiemo,
Thanks for your reply. For most cases rosbag record and play would do. 

However, I wanted to record Kinect2 frames in synchronization with a motion capture system and a humanoid robot for aligned datasets. To solve this problem, I included ZeroMQ interface with the recorder to communicate with a client which was also communicating with the Mocap system.

This could be one specific use-case for the recorder when we want to record frames at specific  time instances. I found very few references for using the rosbag api and it took some time for me. So I thought it might be help to others.

Cheers,
Nishanth

**Comment by wiedemeyer** [comment]
Hi,
I though a lot about this pull request and I decided to not merge it in. I think using the rosbag tool is sufficient for most users. I hope you can understand my decision.
I think the best solution would be, if you place your tools as standalone tools in a own separate public github, so that people who need the functionality could look it up there.

**Pull request closed without merging**
