### PR TITLE
Add KDE depth unwrapping support

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Hi, this is a trivial PR to add support to the newly added KDE depth unwrapping introduced in libfreenect2: https://github.com/OpenKinect/libfreenect2/commit/ff7ae0bdaed772fcabf0fb687341e863deae4be9

The only issue is that compilation will break if libfreenect2 isn't up-to-date. However, there is no versioning support so I don't see an easy way around this.

Best, Tobias

### CODE REVIEW

**Comment by wiedemeyer** [comment]
Hi,
thanks for the PR. It is looking good. Could you also add the new processors to the `help` function at the end, so that it prints all supported depth processors correctly?

**Comment by Tobias-Fischer** [comment]
Sure, done.

**Comment by dwhit** [comment]
Any update on merging this? I've been using Tobias's fork and it hasn't caused any problems for me. Thanks!

**Comment by wiedemeyer** [comment]
Sorry, I just forgot to merge it in.

**Pull request merged**
